image: openjdk:11-jdk

cache:
  key: "${CI_COMMIT_SHA}"
  untracked: true
  paths:
    - .gradle/

before_script:
  - chmod +x ./gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - export CHROME_BIN='chromium-browser'

stages:
  - inception
  - assess
  - test
  - assemble

create-cache:
  stage: inception
  script:
    - ./gradlew -v
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: push
    untracked: true
    paths:
    - .gradle/

common-assess:
  stage: assess
  script:
    - ./gradlew assessCommon
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/

project-assess:
  stage: assess
  script:
    - ./gradlew assessGradle
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/

code-assess:
  stage: assess
  script:
    - ./gradlew assess
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/

code-tests:
  stage: test
  script:
    - ./gradlew test
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
  artifacts:
    reports:
      junit: build/test-results/test/TEST-*.xml
  artifacts:
    name: $CI_PROJECT_NAME-coverage-$CI_COMMIT_SHORT_SHA
    paths:
      - build/reports/jacoco/test/html

code-build:
  stage: assemble
  script:
    - ./gradlew assemble
  cache:
    key: "${CI_COMMIT_SHA}"
    policy: pull
    untracked: true
    paths:
      - .gradle/
  artifacts:
    name: $CI_PROJECT_NAME-artifact-$CI_COMMIT_SHORT_SHA
    paths:
      - build/libs
